# Importing the necessary libraries

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt       
import seaborn as sns

# Loading the dataset

In [2]:
df=pd.read_csv("houseprice.csv")

In [3]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

# EDA

In [4]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [6]:
df.dtypes

Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
                  ...
MoSold             int64
YrSold             int64
SaleType          object
SaleCondition     object
SalePrice          int64
Length: 81, dtype: object

In [7]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [8]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [10]:
for i in df:
    print(df[i].isnull().sum())

0
0
0
259
0
0
1369
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
8
8
0
0
0
37
37
38
37
0
38
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
690
81
81
81
0
0
81
81
0
0
0
0
0
0
0
1453
1179
1406
0
0
0
0
0
0

In [11]:
for i in df.select_dtypes('object'):
    df.drop(i, inplace = True, axis = 1)

In [12]:
df

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,40,0,0,0,0,0,8,2007,175000
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,349,0,0,0,0,0,0,2,2010,210000
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,60,0,0,0,0,2500,5,2010,266500
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,366,0,112,0,0,0,0,4,2010,142125
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,736,68,0,0,0,0,0,6,2008,147500

In [15]:
df.isnull().sum()

Id                 0
MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64

In [16]:
df['LotFrontage'].fillna(df['LotFrontage'].mean(),inplace=True)

In [17]:
df['GarageYrBlt'].fillna(df['GarageYrBlt'].mean(),inplace=True)

In [21]:
df['MasVnrArea'].fillna(df['MasVnrArea'].mean(),inplace=True)

In [22]:
df.isnull().sum()

Id               0
MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SalePrice        0
dtype: int64

In [23]:
x=df.drop(["SalePrice","Id"],axis=1)
y=df['SalePrice']

In [25]:
from scipy.stats import zscore
XScaled=x.apply(zscore)

In [26]:
from sklearn.decomposition import PCA

In [27]:
covMatrix = np.cov(XScaled,rowvar=False)
print(covMatrix)

[[ 1.0006854  -0.3573006  -0.13987689 ... -0.00768856 -0.01359395
  -0.02142171]
 [-0.3573006   1.0006854   0.30700488 ...  0.00116908  0.01016477
   0.00677289]
 [-0.13987689  0.30700488  1.0006854  ...  0.03809378  0.00120581
  -0.01427118]
 ...
 [-0.00768856  0.00116908  0.03809378 ...  1.0006854  -0.006499
   0.00490963]
 [-0.01359395  0.01016477  0.00120581 ... -0.006499    1.0006854
  -0.14582129]
 [-0.02142171  0.00677289 -0.01427118 ...  0.00490963 -0.14582129
   1.0006854 ]]

In [28]:
pca = PCA(n_components=36)
pca.fit(XScaled)

PCA(n_components=36)

In [29]:
print(pca.explained_variance_)

[7.13724621e+00 3.20640438e+00 2.57539187e+00 2.02337917e+00
 1.47841346e+00 1.19403196e+00 1.15264652e+00 1.13358732e+00
 1.10866305e+00 1.08654497e+00 1.04729157e+00 1.02150500e+00
 1.01165980e+00 9.56320538e-01 9.17858928e-01 8.99007406e-01
 8.45352464e-01 8.13043034e-01 7.84495632e-01 7.36959123e-01
 6.73514640e-01 6.24638961e-01 5.87338889e-01 5.40529038e-01
 4.30161489e-01 3.89515133e-01 3.13544726e-01 2.81191557e-01
 2.56942070e-01 2.39929707e-01 1.94123704e-01 1.42737060e-01
 1.26107357e-01 9.45977119e-02 1.40757363e-30 3.02018935e-32]

In [30]:
print(pca.components_)

[[-1.62880985e-02  1.61076665e-01  1.06869554e-01 ... -1.09745493e-02
   2.19028802e-02 -1.33671303e-02]
 [ 1.65104510e-01 -1.18737226e-02 -3.07829151e-02 ...  2.67599674e-02
   2.85988995e-02 -3.62400421e-02]
 [-2.25784852e-01  2.75946646e-01  2.80158447e-01 ...  4.22869522e-02
  -4.57853902e-03  1.38326802e-03]
 ...
 [-2.61874888e-02  1.77169658e-02 -4.11318128e-03 ...  1.22121964e-02
  -4.46476099e-03  6.84803833e-03]
 [-1.33341580e-16 -1.73244812e-16  9.83400426e-18 ... -1.11566995e-16
  -4.11440642e-17  1.31105441e-16]
 [-0.00000000e+00  5.18606902e-16  8.97791185e-17 ... -7.50670265e-17
   2.02235503e-16  5.80366501e-17]]

In [31]:
print(pca.explained_variance_ratio_)

[1.98121047e-01 8.90057837e-02 7.14896640e-02 5.61664803e-02
 4.10389123e-02 3.31448369e-02 3.19960288e-02 3.14669693e-02
 3.07751027e-02 3.01611323e-02 2.90715069e-02 2.83557039e-02
 2.80824133e-02 2.65462646e-02 2.54786183e-02 2.49553235e-02
 2.34659293e-02 2.25690599e-02 2.17766196e-02 2.04570655e-02
 1.86959258e-02 1.73391979e-02 1.63037945e-02 1.50044115e-02
 1.19407461e-02 1.08124540e-02 8.70361025e-03 7.80552666e-03
 7.13239117e-03 6.66014921e-03 5.38863173e-03 3.96220264e-03
 3.50058285e-03 2.62591441e-03 3.90724871e-32 8.38366867e-34]

In [32]:
pca.explained_variance_ratio_.sum()

0.9999999999999999

In [34]:
c=1
for i in pca.explained_variance_ratio_:
    print(i,c)
    c=c+1

0.19812104668235966 1
0.08900578365174744 2
0.0714896639527746 3
0.05616648025584465 4
0.041038912331839206 5
0.0331448368530341 6
0.03199602876648253 7
0.031466969287964906 8
0.03077510266233988 9
0.03016113231842485 10
0.029071506853435836 11
0.02835570386775406 12
0.028082413268607293 13
0.026546264564412714 14
0.025478618252990623 15
0.024955323549633594 16
0.023465929313124044 17
0.02256905986518397 18
0.021776619608568182 19
0.02045706546165591 20
0.01869592579073434 21
0.017339197946495986 22
0.016303794516147153 23
0.015004411450249923 24
0.011940746052833857 25
0.01081245395055905 26
0.00870361025344401 27
0.007805526659911739 28
0.007132391171040403 29
0.006660149211527867 30
0.005388631731898543 31
0.003962202635915617 32
0.00350058284682701 33
0.0026259144142364538 34
3.9072487057295146e-32 35
8.38366867276761e-34 36

## Dimensionality reduction

In [35]:
pca3 = PCA(n_components=10)
pca3.fit(XScaled)
print(pca3.components_)
print(pca3.explained_variance_ratio_)
Xpca3 = pca3.transform(XScaled)

[[-1.62883933e-02  1.61075572e-01  1.06868056e-01  3.01748415e-01
  -8.34000060e-02  2.37722677e-01  2.08698784e-01  1.95978965e-01
   1.40427480e-01 -1.23732722e-02  1.16726098e-01  2.59012274e-01
   2.57041302e-01  1.33689822e-01 -1.08406263e-02  2.99157351e-01
   7.46531098e-02 -1.30008768e-02  2.61822699e-01  1.26037298e-01
   1.12726986e-01 -1.71975540e-02  2.40360878e-01  1.83384572e-01
   2.21044893e-01  2.83262214e-01  2.79006790e-01  1.33560291e-01
   1.49336503e-01 -7.46839947e-02  1.66530839e-02  3.06916540e-02
   5.00106011e-02 -1.09741917e-02  2.19025231e-02 -1.33658318e-02]
 [ 1.65104377e-01 -1.18224866e-02 -3.06126549e-02 -1.85001922e-02
   6.07263020e-02 -1.97506419e-01 -8.71956957e-02 -2.05428794e-02
  -2.90310675e-01 -7.01297082e-02  1.14833424e-01 -2.11947103e-01
  -1.54874959e-01  4.30724777e-01  1.19344919e-01  2.54916787e-01
  -2.89015150e-01  4.00387697e-03  1.49864479e-01  2.22550192e-01
   3.63242723e-01  1.74394817e-01  3.28937773e-01  1.27328764e-02
  -1.37470253e-01 -6.85797423e-02 -1.01586299e-01 -6.81100543e-02
   3.93348547e-02  1.18049958e-01 -3.03375076e-02  1.69826307e-02
   1.38490809e-02  2.67343847e-02  2.86093925e-02 -3.64090394e-02]
 [-2.25821044e-01  2.75899123e-01  2.79886710e-01 -1.06164203e-01
   1.32321997e-01 -3.23625311e-01 -2.66035005e-01  2.13285504e-03
   2.20656864e-01  1.72270077e-01 -1.03731930e-01  1.88272038e-01
   2.63446859e-01 -6.96052549e-02  9.22225912e-02  1.44524518e-01
   1.57312773e-01  7.13709838e-02 -1.19582671e-01 -1.38028119e-01
   1.54294360e-01  5.80383110e-02  1.35270386e-01  1.99822114e-01
  -3.55616508e-01 -9.53082710e-02 -3.38502289e-02  2.32756834e-02
  -1.49082627e-02  1.84004294e-01  3.09869025e-03  1.24250113e-01
   1.57712956e-01  4.22686438e-02 -4.52626915e-03  1.86106153e-03]
 [-2.98813792e-01  1.31076718e-01 -3.02494430e-02  7.17913561e-03
  -9.08241897e-02 -3.07926304e-02 -2.78509345e-02 -4.91989497e-02
  -3.37408901e-01 -9.11320237e-02  5.66958806e-01  1.86748256e-01
   2.06911919e-01 -2.60889942e-01  2.86642840e-02 -6.18529687e-02
  -3.57658985e-01 -4.16147353e-02  6.41614830e-02 -3.10341561e-01
   3.54705671e-02  4.32725700e-02  3.87520823e-03 -1.03477779e-01
  -3.23679209e-04  2.78993789e-02  3.15042959e-02 -1.38654605e-01
  -3.27446202e-02  5.96038696e-02  5.07961088e-02 -6.16319056e-02
  -7.54241085e-02 -2.21029991e-02  4.37046345e-02 -4.64532319e-02]
 [ 3.04236966e-01 -6.30490523e-02 -3.33691703e-02 -1.30625292e-01
  -3.83838926e-01  2.08250312e-02 -1.48815910e-01  1.73441753e-02
   1.45498281e-01 -8.46301133e-02 -5.20283549e-02  6.77434430e-02
   1.34542154e-01 -9.19452176e-02  3.15939989e-02  2.55230124e-02
   2.20907402e-01 -2.36510574e-01  1.52538547e-01 -2.04882226e-01
   7.42636405e-02  5.82450273e-01  1.12656248e-01 -1.86814513e-01
   5.95924506e-02 -1.83683915e-02 -1.36178279e-02 -4.49882650e-02
  -1.54092092e-01  4.66038485e-02 -7.36917227e-02 -2.07394267e-01
  -6.63253852e-03  7.33453111e-04 -7.29034537e-02  5.55766927e-02]
 [ 1.61560284e-01 -1.46881173e-01 -6.56161791e-02 -5.11960332e-03
  -2.25736153e-01  9.05271307e-03 -2.11439834e-01  1.07205650e-01
   6.57105526e-02 -4.93646623e-02 -7.45781882e-03  4.26519156e-02
   4.17684945e-02 -5.07694627e-02 -8.11592783e-02 -1.89566363e-02
  -5.79449599e-02  2.10802235e-01 -3.70552699e-02 -3.24350560e-03
  -5.19389042e-02  7.78140536e-02 -5.55484800e-02  1.22590378e-01
  -7.00173111e-02  2.82761471e-02  7.48326109e-03 -1.43220216e-01
   1.30162586e-01 -1.17845219e-01 -4.35553546e-02  2.88907063e-01
   2.53229861e-02 -8.50635495e-02  5.18292704e-01 -5.70825669e-01]
 [ 9.11659756e-02 -8.15097643e-02  8.07638270e-02 -3.63947228e-02
   3.32282627e-01  1.49812176e-03  2.09070887e-01 -8.00452516e-02
   3.06805412e-02  6.14818972e-02 -5.81782045e-02 -4.09266716e-03
   6.85508624e-02 -6.60861397e-02 -5.90769595e-02 -9.93388205e-03
  -7.81955371e-02  5.21479538e-01  1.37055108e-01 -1.99173425e-01
   9.44133453e-02  2.33346188e-01  5.37165928e-02 -1.31474074e-01
   3.86037758e-02 -3.52950867e-02 -4.59634590e-02  3.26009468e-01
  -1.19579473e-01 -1.38966555e-01  2.69772144e-01 -2.57221897e-01
  -3.05075027e-02  1.77145819e-01  2.42686817e-01 -3.08641379e-02]
 [ 1.32233429e-01 -9.72914800e-02 -1.00674223e-01  9.90199752e-02
   1.15371909e-01 -3.56428250e-02  2.11718861e-01 -2.94042713e-01
  -1.43203316e-02  1.20629391e-01  4.89314519e-02  7.87534583e-02
   3.10637686e-02 -2.56516073e-02  5.16628154e-01  4.93477391e-02
   1.14177201e-01 -1.51437009e-01  7.13490484e-02 -1.60356198e-01
  -8.13648740e-02 -1.16972176e-01 -2.53883083e-02 -1.03797912e-01
   1.26253668e-01 -1.35245374e-01 -9.93336113e-02  8.74873706e-02
   2.57102847e-01  1.90662670e-01 -1.61042000e-01 -8.03943966e-02
   3.95611500e-01  1.05867648e-02  7.19158690e-02 -2.56969007e-01]
 [ 2.13501014e-01 -2.55642889e-01 -6.45347472e-02  5.95723906e-02
   1.65016737e-01 -2.69588468e-02  9.45315545e-02  4.85568116e-04
  -1.01064405e-01  2.95518238e-01  1.02461844e-01  1.06796079e-01
   1.27064679e-01 -1.04015536e-01  4.97461499e-02  1.16744963e-02
  -2.25536890e-02  1.86981788e-02  8.51008635e-02 -1.13045413e-01
  -6.83209644e-02  1.82582150e-01  1.64425246e-02  1.42402461e-01
  -1.14160885e-02 -7.50348051e-02 -9.93280232e-02 -7.34821502e-02
   9.66337585e-02 -2.21684527e-01 -2.13858428e-01  5.51073992e-01
  -1.83868444e-01  1.93547724e-01 -1.03696441e-01  3.24117324e-01]
 [-1.41159313e-01  1.03006083e-01  2.45590428e-01 -1.51742867e-01
  -3.25400500e-01  1.61020095e-01 -1.00372153e-01 -1.60870367e-01
  -2.14919691e-01  5.53928303e-01 -3.77351989e-02 -5.77587870e-02
  -5.93350065e-02 -8.53096837e-03  7.68520256e-03 -5.00275915e-02
  -4.39741525e-02  8.43937968e-02  1.40135885e-02  1.00773500e-01
   1.62962970e-01 -3.47317900e-02  2.23106523e-02 -7.51888729e-02
   1.12683244e-01 -1.28185527e-02 -3.69780972e-02  2.84080597e-01
  -5.85434947e-02 -2.41081409e-01 -3.33175251e-01 -5.88949646e-02
  -6.41102902e-03 -1.54308873e-01 -9.77275313e-03 -7.86846631e-02]]
[0.19812105 0.08900573 0.07148921 0.05616439 0.04101539 0.0331106
 0.03190429 0.03143183 0.0306881  0.03012711]

In [36]:
Xpca3

array([[ 1.46683967e+00,  3.74186518e-01, -1.69999125e+00, ...,
        -2.23432742e-01, -5.19447731e-01,  3.01818153e-03],
       [-3.46315795e-02, -1.05740309e+00,  1.25761509e+00, ...,
        -5.14750249e-01, -2.26250188e-01,  1.93274864e-01],
       [ 1.65310395e+00,  2.51851027e-01, -1.47672644e+00, ...,
        -2.11731039e-01, -5.47675145e-01, -8.24461748e-03],
       ...,
       [ 4.81553624e-01,  3.33237253e+00,  1.64361857e+00, ...,
         2.46936299e-01,  2.81739336e+00, -2.63116965e+00],
       [-2.82435944e+00, -1.99968468e+00,  1.97411280e+00, ...,
         1.13389993e+00,  1.71959325e+00,  3.57601054e+00],
       [-8.65018851e-01, -1.49644283e+00,  1.58992563e+00, ...,
         5.06736391e-01, -5.07267952e-01,  2.66932769e+00]])

# Modelling

In [38]:
from sklearn.linear_model import LinearRegression
regression_model = LinearRegression()
regression_model.fit(XScaled, y)
regression_model.score(XScaled, y)

0.813111128495434

In [39]:
regression_model_pca = LinearRegression()
regression_model_pca.fit(Xpca3, y)
regression_model_pca.score(Xpca3, y)

0.7752132151588349